@startuml ListTrips

skinparam sequenceMessageAlign center
skinparam RoundCorner 15
title ListTrips


participant View as v
participant Controller as c
participant ClientModel as m
participant ClientService as s

v -> c : List Trips
activate v
activate c

c -> s : getTrips()
activate s

s -> m : Trip [ ]
activate m

m -> s : Trip [ ]
deactivate s




