@startuml Update Issue

skinparam sequenceMessageAlign center
skinparam RoundCorner 15
title Update Issue

participant View as v
participant Component as c
participant Service as s


[o-> v: Begins Search
activate v

v --> c: Inicializes View search

[<-- v: Request Issue info

[o-> v: Inserts Info

v -> c: onConfirmClick ()
activate c

c -> c: onCloseIssue ()

c -> s: updateIssue ()
activate s

s ->o]: updateIssue ()

s <--]: Issue Updated

s --> c: Issue Updated
deactivate s

c --> v: Issue Updated
deactivate c

[<-- v: Displays confirmation message